future: true
collections:
  youth:
    output: true
  events:
    output: true
  groups:
    output: true
  leaders:
    output: true
  volunteer_groups:
    output: true
  announcements:
    output: true
