backend:
  name: github
  repo: CornerstonePres/cornerstone-pres
  branch: master

media_folder: "images/uploads"
logo_url: /svg/rainshade.svg
display_url: http://localhost:4000/
collections:
  - name: "site-pages"
    label: Site Pages
    files:
      - label: "Home Page"
        name: "home"
        file: "_data/home.yml"
        fields:
          - label: "Mission Statement"
            name: "mission-statement"
            widget: "string"
          - label: "Featured Content"
            name: "featured-content"
            widget: "object"
            fields:
            - label: "Featured Content 1"
              name: "featured-content-1"
              widget: "object"
              fields:
                - label: "Title"
                  name: "title"
                  widget: "string"
                - label: "Description"
                  name: "description"
                  widget: "string"
                - label: "Content Link"
                  name: "content_link"
                  widget: "string"
                - label: "Image"
                  name: "image"
                  widget: "image"
            - label: "Featured Content 2"
              name: "featured-content-2"
              widget: "object"
              fields:
                - label: "Title"
                  name: "title"
                  widget: "string"
                - label: "Description"
                  name: "description"
                  widget: "string"
                - label: "Content Link"
                  name: "content_link"
                  widget: "string"
                - label: "Image"
                  name: "image"
                  widget: "image"
            - label: "Featured Content 3"
              name: "featured-content-3"
              widget: "object"
              fields:
                - label: "Title"
                  name: "title"
                  widget: "string"
                - label: "Description"
                  name: "description"
                  widget: "string"
                - label: "Content Link"
                  name: "content_link"
                  widget: "string"
                - label: "Image"
                  name: "image"
                  widget: "image"
          - label: "Service Details"
            name: "service_details"
            widget: "object"
            fields:
              - label: "Service Time"
                name: "service_time"
                widget: "string"
              - label: "Location"
                name: "location"
                widget: "string"
              - label: "Google Maps Link"
                name: "map_link"
                widget: "string"
              - label: "Parking Description"
                name: "parking_description"
                widget: "string"
      - label: "About Page"
        name: "about"
        file: "_data/about.yml"
        fields:
          - label: "Service Details"
            name: "service_details"
            widget: "object"
            fields:
              - label: "Content"
                name: "content"
                widget: "markdown"
          - label: "Contact"
            name: "contact"
            widget: "object"
            fields:
              - label: "Phone Number"
                name: "tel"
                widget: "string"
              - label: "Phone Number Display"
                name: "tel_display"
                widget: "string"
              - label: "Email Adress"
                name: "email"
                widget: "string"
          - label: "Core Beliefs"
            name: "core_beliefs"
            widget: "object"
            fields:
              - label: "Content"
                name: "content"
                widget: "markdown"
      - label: "Services & Sermons Page"
        name: "services_sermons"
        file: "_data/services_sermons.yml"
        fields:
          - label: "What To Expect"
            name: "what_to_expect"
            widget: "object"
            fields:
              - label: "Content"
                name: "content"
                widget: "markdown"
          - label: "Past Sermons"
            name: "past_sermons"
            widget: "object"
            fields:
              - label: "Featured Sermon Video ID"
                name: "featured_sermon_video_id"
                widget: "string"
              - label: "Youtube Channel Link"
                name: "youtube_channel_link"
                widget: "string"
      - label: "Volunteer & Give"
        name: "volunteer_give"
        file: "_data/volunteer_give.yml"
        fields:
          - label: "Give an Offering"
            name: "give_an_offering"
            widget: "object"
            fields:
              - label: "Content"
                name: "content"
                widget: "markdown"
  - label: "Youth Activity"
    name: "youth"
    folder: "_youth"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Content"
        name: "body"
        widget: "markdown"
  - label: "Event"
    name: "events"
    folder: "_events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "body"
        widget: "markdown"
      - label: "Date"
        name: "date"
        widget: "datetime"
        default: ""
        dateFormat: "DD.MM.YYYY"
        format: "LLL"
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "event"
      - label: "Location"
        name: "location"
        widget: "string"
      - label: "Google Maps Link"
        name: "map_link"
        widget: "string"
      - label: "Banner Image"
        name: "banner_image"
        widget: "image"
        default: "/images/uploads/holding_hands.jpg"
  - label: "Small Group"
    name: "groups"
    folder: "_groups"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Content"
        name: "body"
        widget: "markdown"
  - label: "Leadership Member"
    name: "leaders"
    folder: "_leaders"
    create: true
    fields:
      - label: "Name"
        name: "title"
        widget: "string"
      - label: "Title / Role"
        name: "title_role"
        widget: "string"
      - label: "Optional Photo"
        name: "photo"
        widget: "image"
      - label: "Portrait Image"
        name: "portrait"
        widget: "boolean"
      - label: "Content"
        name: "body"
        widget: "markdown"
  - label: "Volunteer Group"
    name: "volunteer_groups"
    folder: "_volunteer_groups"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Content"
        name: "body"
        widget: "markdown"
  - label: "Pastor"
    name: "pastor"
    files:
      - label: "Pastor"
        name: "pastor"
        file: "_data/pastor.yml"
        fields:
          - label: "Name"
            name: "name"
            widget: "string"
          - label: "Content"
            name: "content"
            widget: "markdown"
